using BookBuddy.App_Data.Models;

namespace BookBuddy.Business.Helpers
{
    public class InitialBookData
    {
        public static List<Book> BookDropdownItemsSV => new List<Book>
    {
        new Book { BookId = 62301, Title = "Kanotkamrater: En Berättelse om Floridas Rev och Everglades", Language = "sv" },
        new Book { BookId = 61804, Title = "Styr Åt sidan: En Berättelse", Language = "sv" },
        new Book { BookId = 61295, Title = "Små Vandrare", Language = "sv" },
        new Book { BookId = 60625, Title = "Farbror Vigglys Sagobok", Language = "sv" },
        new Book { BookId = 60207, Title = "Vackra Verser för Alla Goda Barn: I Ord på En, Två och Tre Stavelser", Language = "sv" },
        new Book { BookId = 56594, Title = "Förståndare för Lägre Skolan", Language = "sv" },
        new Book { BookId = 54755, Title = "Pojkscouterna på Skogshantverkslägret", Language = "sv" },
        new Book { BookId = 53420, Title = "Frank Nelson i Förkastellen; Eller, Sportklubben Bland Valfångarna", Language = "sv" },
        new Book { BookId = 52755, Title = "Farbror Sams Pojkar på Fälttjänst; eller, Vinnande av Korpralsgaloner", Language = "sv" },
        new Book { BookId = 52257, Title = "När Sarah Räddade Dagen", Language = "sv" },
        new Book { BookId = 52017, Title = "En Pojkes Förmögenhet; Eller, Ben Bakers Märkliga Äventyr", Language = "sv" },
        new Book { BookId = 46227, Title = "Livet och Tiden för Col. Daniel Boone, Jägare, Soldat och Pionjär: Med Skisser av Simon Kenton, Lewis Wetzel och Andra Ledare i Västerlandets Bosättning", Language = "sv" },
        new Book { BookId = 45963, Title = "Mildred Hemma: Med Något om Hennes Släktingar och Vänner. En Fortsättning på Mildreds Gifta Liv", Language = "sv" },
        new Book { BookId = 45859, Title = "Patrañas; eller, Spanska Sagor, Legendariska och Traditionella", Language = "sv" },
        new Book { BookId = 45576, Title = "Motorpojkarna över Klippiga Bergen; Eller, Ett Luftrymmet", Language = "sv" },
        new Book { BookId = 45416, Title = "Gudar och Hjältar; eller, Jupiters Rike", Language = "sv" },
        new Book { BookId = 45405, Title = "Picketts Gap", Language = "sv" },
        new Book { BookId = 45326, Title = "Motorpojkarna i Molnen; eller, En Resa för Berömmelse och Förmögenhet", Language = "sv" },
        new Book { BookId = 45232, Title = "Den Blinde Brodern: En Berättelse från Pennsylvanias Kolgruvor", Language = "sv" },
        new Book { BookId = 45142, Title = "Weatherbys Inning: En Berättelse om College Livet och Baseball", Language = "sv" },
        new Book { BookId = 45140, Title = "På Din Mark! En Berättelse om College Livet och Idrott", Language = "sv" },
        new Book { BookId = 44951, Title = "Motorpojkarna i Främmande Vatten; eller, Vilse i en Flytande Skog", Language = "sv" },
        new Book { BookId = 44846, Title = "Motorpojkarna på Atlanten; eller, Fyrenmysteriet", Language = "sv" },
        new Book { BookId = 43169, Title = "Filippa", Language = "sv" },
        new Book { BookId = 40689, Title = "Ut till Sjöss: Den Glada Jack Junkers Äventyr på Vägen till Berömmelse", Language = "sv" },
        new Book { BookId = 34493, Title = "Dra Svärd! I Hästartilleriet", Language = "sv" },
        new Book { BookId = 31103, Title = "En Julhälsning: En Serie Berättelser", Language = "sv" },
        new Book { BookId = 27222, Title = "Plåtlådan och Vad den Innehöll", Language = "sv" },
        new Book { BookId = 27174, Title = "Kapten Jim", Language = "sv" },
        new Book { BookId = 25302, Title = "Jack: 1877", Language = "sv" },
        new Book { BookId = 20717, Title = "Flickan på Båten", Language = "sv" },
        new Book { BookId = 19043, Title = "De Fruktansvärda Tvillingarna", Language = "sv" },
        new Book { BookId = 18786, Title = "Förräderi i Yttre Rymden", Language = "sv" },
        new Book { BookId = 16663, Title = "Berättelsen om Salomon Ugglan", Language = "sv" },
        new Book { BookId = 16537, Title = "Myter Som Varje Barn Bör Känna till: Ett Urval av Klassiska Myter för Unga Människor", Language = "sv" },
        new Book { BookId = 15825, Title = "Ny Nationell Fjärde Läsbok", Language = "sv" },
        new Book { BookId = 15343, Title = "En Liten Bok för Julen", Language = "sv" },
        new Book { BookId = 13946, Title = "Läger och Stig: En Berättelse från Maine-skogen", Language = "sv" },
        new Book { BookId = 13707, Title = "Två gånger berättade sagor", Language = "sv" },
        new Book { BookId = 13215, Title = "Edwy den Rättvisa eller den Första Krönikan om Aescendune: En Berättelse från Saint Dunstans Tid", Language = "sv" },
        new Book { BookId = 13146, Title = "Skönheten och Bolsjeviken", Language = "sv" },
        new Book { BookId = 12855, Title = "De Elisabetanska Sjöhundarna: En Krönika om Drake och Hans Kamrater", Language = "sv" },
        new Book { BookId = 11716, Title = "Balkan: En Historia om Bulgarien—Serbien—Grekland—Rumänien—Turkiet", Language = "sv" },
        new Book { BookId = 11140, Title = "Rollo på Lek; Eller, Säkra Nöjen", Language = "sv" },
        new Book { BookId = 10366, Title = "Frihetens Kamp: En Omfattande Samling av Skrifter och Tal om Den Nuvarande Situationen", Language = "sv" },
        new Book { BookId = 10070, Title = "Berättelser om Stora Amerikaner för Små Amerikaner", Language = "sv" },
        new Book { BookId = 8730, Title = "En Liten Bushflicka", Language = "sv" },
            new Book { BookId = 6357, Title = "Snöflingor och Solstrålar; Eller, De Unga Pälshandlarna: En Berättelse från Det Fjärran Nord", Language = "sv" },
            new Book { BookId = 5676, Title = "En Dubbel Berättelse", Language = "sv" },
            new Book { BookId = 5673, Title = "Den Unga Musikern; Eller, Kämpande På Sin Väg", Language = "sv" },
            new Book { BookId = 5348, Title = "Trasige Dick, Eller, Gatloppet i New York med Skoputsarna", Language = "sv" },
            new Book { BookId = 5343, Title = "Regnbågsvägen", Language = "sv" },
            new Book { BookId = 5004, Title = "Motorpojkarna på Stilla Havet; Eller, De Unga Vrakjägarna", Language = "sv" },
            new Book { BookId = 4997, Title = "Två Pojkar och en Förmögenhet; Eller, Tylers Testamente", Language = "sv" },
            new Book { BookId = 4992, Title = "Diddie, Dumps och Tot; Eller, Plantageliv för Barn", Language = "sv" },
            new Book { BookId = 4989, Title = "En Söt Flicka som Student", Language = "sv" },
            new Book { BookId = 4988, Title = "Utomhusflickorna på Wild Rose Lodge; Eller, Eremiten vid Månljusfallen", Language = "sv" },
            new Book { BookId = 4987, Title = "Utomhusflickorna vid Regnbågssjön; Eller, Den Spännande Kryssningen av Motorbåten Gem", Language = "sv" },
            new Book { BookId = 4980, Title = "Gamla Farmor Räv", Language = "sv" },
            new Book { BookId = 4357, Title = "Amerikanska Sagor", Language = "sv" },
            new Book { BookId = 4274, Title = "Hustrur och Döttrar", Language = "sv" },
            new Book { BookId = 4018, Title = "Japanska Sagor", Language = "sv" },
            new Book { BookId = 3282, Title = "Den Bruna Sagoboken", Language = "sv" },
            new Book { BookId = 3230, Title = "Sängöverkastets Saga", Language = "sv" },
            new Book { BookId = 3152, Title = "De Yngres Klassiska Verk, Volym 1: Sagor och Undersagor", Language = "sv" },
            new Book { BookId = 2667, Title = "Wakefields Kyrkoherde", Language = "sv" },
            new Book { BookId = 2474, Title = "Cirkuspojkarna på Flygande Ringen", Language = "sv" },
            new Book { BookId = 2435, Title = "Den Röda Sagoboken", Language = "sv" },
            new Book { BookId = 2226, Title = "Kim", Language = "sv" },
            new Book { BookId = 2129, Title = "Murad den Olycklige och Andra Berättelser", Language = "sv" },
            new Book { BookId = 1286, Title = "Shakespeare-sagor", Language = "sv" },
            new Book { BookId = 959, Title = "Den Förlorade Prinsessan av Oz", Language = "sv" },
            new Book { BookId = 902, Title = "Den Glada Prinsen och Andra Sagor", Language = "sv" },
            new Book { BookId = 837, Title = "Amulettens Historia", Language = "sv" },
            new Book { BookId = 699, Title = "En Barnhistoria om England", Language = "sv" },
            new Book { BookId = 540, Title = "Den Röda Sagoboken", Language = "sv" },
            new Book { BookId = 514, Title = "Unga Kvinnor", Language = "sv" },
            new Book { BookId = 507, Title = "Adam Bede", Language = "sv" },
            new Book { BookId = 289, Title = "Vind i Pilen", Language = "sv" },
            new Book { BookId = 236, Title = "Djungelboken", Language = "sv" },
            new Book { BookId = 209, Title = "Vändningen av Skruven", Language = "sv" },
            new Book { BookId = 163, Title = "Blomsagor", Language = "sv" },
            new Book { BookId = 153, Title = "Jude den Mörka", Language = "sv" },
            new Book { BookId = 141, Title = "Mansfield Park", Language = "sv" },
            new Book { BookId = 113, Title = "Den Hemliga Trädgården", Language = "sv" },
            new Book { BookId = 110, Title = "Tess av d'Urbervilles: En Ren Kvinna", Language = "sv" },
            new Book { BookId = 76, Title = "Huckleberry Finns Äventyr", Language = "sv" },
            new Book { BookId = 55, Title = "Den Underbara Trollkarlen från Oz", Language = "sv" },
            new Book { BookId = 54, Title = "Det Märkliga Landet Oz", Language = "sv" },
            new Book { BookId = 51, Title = "Anne från Ön", Language = "sv" },
            new Book { BookId = 45, Title = "Anne på Grönkulla", Language = "sv" },
            new Book { BookId = 44, Title = "Larkens Sång", Language = "sv" },
            new Book { BookId = 33, Title = "Den Röda Bokstaven", Language = "sv" },
            new Book { BookId = 19, Title = "Hiawathas Sång", Language = "sv" },
            new Book { BookId = 16, Title = "Peter Pan", Language = "sv" },
            new Book { BookId = 13, Title = "Snarkens Jakt: En Sorg i Åtta Passager", Language = "sv" },
            new Book { BookId = 12, Title = "Genom Spegeln", Language = "sv" },
            new Book { BookId = 11, Title = "Alice i Underlandet", Language = "sv" }
    };
        public static List<Book> BookDropdownItemsEN => new List<Book>
    {
        new Book { BookId = 62301, Title = "Canoemates: A Story of the Florida Reef and Everglades", Language = "en" },
        new Book { BookId = 61804, Title = "Sheer Off: A Tale", Language = "en" },
        new Book { BookId = 61295, Title = "Little Wanderers", Language = "en" },
        new Book { BookId = 60625, Title = "Uncle Wiggily's Story Book", Language = "en" },
        new Book { BookId = 60207, Title = "Pretty Verses for All Good Children: In Words of One, Two, and Three Syllables", Language = "en" },
        new Book { BookId = 56594, Title = "Head of the Lower School", Language = "en" },
        new Book { BookId = 54755, Title = "The Boy Scouts of Woodcraft Camp", Language = "en" },
        new Book { BookId = 53420, Title = "Frank Nelson in the Forecastle; Or, The Sportman's Club Among the Whalers", Language = "en" },
        new Book { BookId = 52755, Title = "Uncle Sam's Boys on Field Duty; or, Winning Corporal's Chevrons", Language = "en" },
        new Book { BookId = 52257, Title = "When Sarah Saved the Day", Language = "en" },
        new Book { BookId = 52017, Title = "A Boy's Fortune; Or, The Strange Adventures of Ben Baker", Language = "en" },
        new Book { BookId = 46227, Title = "The Life and Times of Col. Daniel Boone, Hunter, Soldier, and Pioneer: With Sketches of Simon Kenton, Lewis Wetzel, and Other Leaders in the Settlement of the West", Language = "en" },
        new Book { BookId = 45963, Title = "Mildred at Home: With Something About Her Relatives and Friends.: A sequel to Mildred's married life.", Language = "en" },
        new Book { BookId = 45859, Title = "Patrañas; or, Spanish Stories, Legendary and Traditional", Language = "en" },
        new Book { BookId = 45576, Title = "The Motor Boys Over the Rockies; Or, A Mystery of the Air", Language = "en" },
        new Book { BookId = 45416, Title = "Gods and Heroes; or, The Kingdom of Jupiter", Language = "en" },
        new Book { BookId = 45405, Title = "Pickett's Gap", Language = "en" },
        new Book { BookId = 45326, Title = "The Motor Boys in the Clouds; or, A Trip for Fame and Fortune", Language = "en" },
        new Book { BookId = 45232, Title = "The Blind Brother: A Story of the Pennsylvania Coal Mines", Language = "en" },
        new Book { BookId = 45142, Title = "Weatherby's Inning: A Story of College Life and Baseball", Language = "en" },
        new Book { BookId = 45140, Title = "On Your Mark! A Story of College Life and Athletics", Language = "en" },
        new Book { BookId = 44951, Title = "The Motor Boys in Strange Waters; or, Lost in a Floating Forest", Language = "en" },
        new Book { BookId = 44846, Title = "The Motor Boys on the Atlantic; or, The Mystery of the Lighthouse", Language = "en" },
        new Book { BookId = 43169, Title = "Philippa", Language = "en" },
        new Book { BookId = 40689, Title = "Off to Sea: The Adventures of Jovial Jack Junker on his Road to Fame", Language = "en" },
        new Book { BookId = 34493, Title = "Draw Swords! In the Horse Artillery", Language = "en" },
        new Book { BookId = 31103, Title = "A Christmas Greeting: A Series of Stories", Language = "en" },
        new Book { BookId = 27222, Title = "The Tin Box, and What it Contained", Language = "en" },
        new Book { BookId = 27174, Title = "Captain Jim", Language = "en" },
        new Book { BookId = 25302, Title = "Jack: 1877", Language = "en" },
        new Book { BookId = 20717, Title = "The Girl on the Boat", Language = "en" },
        new Book { BookId = 19043, Title = "The Terrible Twins", Language = "en" },
        new Book { BookId = 18786, Title = "Treachery in Outer Space", Language = "en" },
        new Book { BookId = 16663, Title = "The Tale of Solomon Owl", Language = "en" },
        new Book { BookId = 16537, Title = "Myths That Every Child Should Know: A Selection Of The Classic Myths Of All Times For Young People", Language = "en" },
        new Book { BookId = 15825, Title = "New National Fourth Reader", Language = "en" },
        new Book { BookId = 15343, Title = "A Little Book for Christmas", Language = "en" },
        new Book { BookId = 13946, Title = "Camp and Trail: A Story of the Maine Woods", Language = "en" },
        new Book { BookId = 13707, Title = "Twice-told tales", Language = "en" },
        new Book { BookId = 13215, Title = "Edwy the Fair or the First Chronicle of Aescendune: A Tale of the Days of Saint Dunstan", Language = "en" },
        new Book { BookId = 13146, Title = "The Beauty and the Bolshevist", Language = "en" },
         new Book { BookId = 8730, Title = "A Little Bush Maid", Language = "en" },
    new Book { BookId = 6357, Title = "Snowflakes and Sunbeams; Or, The Young Fur-traders: A Tale of the Far North", Language = "en" },
    new Book { BookId = 5676, Title = "A Double Story", Language = "en" },
    new Book { BookId = 5673, Title = "The Young Musician; Or, Fighting His Way", Language = "en" },
    new Book { BookId = 5348, Title = "Ragged Dick, Or, Street Life in New York with the Boot-Blacks", Language = "en" },
    new Book { BookId = 5343, Title = "Rainbow Valley", Language = "en" },
    new Book { BookId = 5004, Title = "The Motor Boys on the Pacific; Or, the Young Derelict Hunters", Language = "en" },
    new Book { BookId = 4997, Title = "Two Boys and a Fortune; Or, The Tyler Will", Language = "en" },
    new Book { BookId = 4992, Title = "Diddie, Dumps, and Tot; Or, Plantation Child-Life", Language = "en" },
    new Book { BookId = 4989, Title = "A Sweet Girl Graduate", Language = "en" },
    new Book { BookId = 4988, Title = "The Outdoor Girls at Wild Rose Lodge; Or, The Hermit of Moonlight Falls", Language = "en" },
    new Book { BookId = 4987, Title = "The Outdoor Girls at Rainbow Lake; Or, The Stirring Cruise of the Motor Boat Gem", Language = "en" },
    new Book { BookId = 4980, Title = "Old Granny Fox", Language = "en" },
    new Book { BookId = 4357, Title = "American Fairy Tales", Language = "en" },
    new Book { BookId = 4274, Title = "Wives and Daughters", Language = "en" },
    new Book { BookId = 4018, Title = "Japanese Fairy Tales", Language = "en" },
    new Book { BookId = 3282, Title = "The Brown Fairy Book", Language = "en" },
    new Book { BookId = 3230, Title = "The Counterpane Fairy", Language = "en" },
    new Book { BookId = 3152, Title = "The Junior Classics, Volume 1: Fairy and wonder tales", Language = "en" },
    new Book { BookId = 2667, Title = "The Vicar of Wakefield", Language = "en" },
    new Book { BookId = 2474, Title = "The Circus Boys on the Flying Rings", Language = "en" },
    new Book { BookId = 2435, Title = "The Crimson Fairy Book", Language = "en" },
    new Book { BookId = 2226, Title = "Kim", Language = "en" },
    new Book { BookId = 2129, Title = "Murad the Unlucky, and Other Tales", Language = "en" },
    new Book { BookId = 1286, Title = "Tales from Shakespeare", Language = "en" },
    new Book { BookId = 959, Title = "The Lost Princess of Oz", Language = "en" },
    new Book { BookId = 902, Title = "The Happy Prince, and Other Tales", Language = "en" },
    new Book { BookId = 837, Title = "The Story of the Amulet", Language = "en" },
    new Book { BookId = 699, Title = "A Child's History of England", Language = "en" },
    new Book { BookId = 540, Title = "The Red Fairy Book", Language = "en" },
    new Book { BookId = 514, Title = "Little Women", Language = "en" },
    new Book { BookId = 507, Title = "Adam Bede", Language = "en" },
    new Book { BookId = 289, Title = "The Wind in the Willows", Language = "en" },
    new Book { BookId = 236, Title = "The Jungle Book", Language = "en" },
    new Book { BookId = 209, Title = "The Turn of the Screw", Language = "en" },
    new Book { BookId = 163, Title = "Flower Fables", Language = "en" },
    new Book { BookId = 153, Title = "Jude the Obscure", Language = "en" },
    new Book { BookId = 141, Title = "Mansfield Park", Language = "en" },
    new Book { BookId = 113, Title = "The Secret Garden", Language = "en" },
    new Book { BookId = 110, Title = "Tess of the d'Urbervilles: A Pure Woman", Language = "en" },
    new Book { BookId = 76, Title = "Adventures of Huckleberry Finn", Language = "en" },
    new Book { BookId = 55, Title = "The Wonderful Wizard of Oz", Language = "en" },
    new Book { BookId = 54, Title = "The Marvelous Land of Oz", Language = "en" },
    new Book { BookId = 51, Title = "Anne of the Island", Language = "en" },
    new Book { BookId = 45, Title = "Anne of Green Gables", Language = "en" },
    new Book { BookId = 44, Title = "The Song of the Lark", Language = "en" },
    new Book { BookId = 33, Title = "The Scarlet Letter", Language = "en" },
    new Book { BookId = 19, Title = "The Song of Hiawatha", Language = "en" },
    new Book { BookId = 16, Title = "Peter Pan", Language = "en" },
    new Book { BookId = 13, Title = "The Hunting of the Snark: An Agony in Eight Fits", Language = "en" },
    new Book { BookId = 12, Title = "Through the Looking-Glass", Language = "en" },
    new Book { BookId = 11, Title = "Alice's Adventures in Wonderland", Language = "en" }
    };

    }
}
